version: '3.1'

services:

  jeremybradfordsr_com:
    image: wordpress
    restart: always
    ports:
      - 5150:5150
    environment:
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_USER: jeremybradfordsr_com
      WORDPRESS_DB_PASSWORD: Thugitout09!_com
      WORDPRESS_DB_NAME: jeremybradfordsr
    volumes:
      - wordpress_jeremybradfordsr_com:/var/www/html

  bradfordgroup_cloud:
    image: wordpress
    restart: always
    ports:
      - 5151:5151
    environment:
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_USER: bradfordgroup_cloud
      WORDPRESS_DB_PASSWORD: Thugitout09!
      WORDPRESS_DB_NAME: bradfordgroup_cloud
    volumes:
      - wordpress_bradfordgroup_cloud:/var/www/html
      
    mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Thugitout09!
    volumes:
      - mariadb:/var/lib/mysql

      

volumes:
  jeremybradfordsr_com:
  bradfordgroup_cloud
  mariadb

 proxy:
    # Pathwae!
    image: quay.io/pathwae/proxy
    ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
    environment:
      CONFIG: |
        jeremybradfordsr.com:
          # foocontainer port 5000
          to: http://jeremybradfordsr.com:5150
          force_ssl: false
        brsdfordgroup.cloud:
          # foocontainer port 5000
          to: http://bradfordgroup.cloud:5151
          force_ssl: false
